### ISSUE TITLE
API considerations for lack of DATAGRAM support

### ISSUE THREAD

**Issue by rpaulo** [tfpauly/draft-pauly-quic-datagram#13]
If an API allows the creation of a QUIC stream before the connection is established, this API might also allow the creation of a DATAGRAM stream.  If the remote endpoint doesn't support the DATAGRAM extension, the implementation can either return an error to the application ("failed to create stream") or it could simply convert the stream abstraction to use QUIC STREAM frames instead.  There are arguments on both sides and it depends on the specific application, but I'm creating this issue because perhaps this ought to be mentioned in the spec.

**Comment by tfpauly** [comment]
While I do agree that this is indeed relevant, I think API mappings is out of scope for this document (as it is for the main transport spec).

**Comment by DavidSchinazi** [comment]
+1. How an application protocol behaves in the absence of a transport protocol feature should be decided by the application. In general I think the approach will be for the application to require this extension and the client will fail if the server doesn't support it - because in that case the server doesn't support our application.
