### ISSUE TITLE
Clarify lost datagram

### ISSUE THREAD

**Issue by mikkelfj** [tfpauly/draft-pauly-quic-datagram#16]
> If a sender detects that a packet containing a specific DATAGRAM frame has been lost, the implementation MAY notify the application that the datagram was lost. Similarly, if a packet containing a DATAGRAM frame is acknowledged, the implementation MAY notify the application that the datagram was successfully transmitted and received.

A lost DATAGRAM is not necessarily lost. It might be received by the peer after it is deemed lost. The late receiving peer cannot trivially be sure the sender thinks the frame is lost so it has a choice to make to drop the DATAGRAM or to give it to the application. Likely it will give it to the application. Hence, a lost DATAGRAM is merely suggestive of a possibly loss, and at least a delayed delivery.

**Comment by mikkelfj** [comment]
Related:

A DATAGRAM that is ACK'ed could presumably be dropped because the application is not able to handle it. It would be possible to treat this a NACK event, but that is possibly coupling things too tightly. What if the application is slow and is later able to receive. The allocated buffer might keep the packet or it might spill when new DATGRAMS arrive, but after ACK processing.

I think some text is needed to explain how tightly or loosely coupled ACK (and NACK) is to actual loss. NACK isn't really a thing, but eventually loss will be declared in QUIC transport if not ACK'ed.

**Comment by mikkelfj** [comment]
FYI: @ianswett

**Comment by ianswett** [comment]
As you said, loss detection thinking a packet is lost is not a guarantee it's lost, though typically it's expected to be correct.  Some implementations could support indicating a Datagram is delivered after it was initially deemed lost, but that would certainly be optional.

And yes, because these are not flow controlled, it's possible that the QUIC transport can process them but the application cannot.  In applications where that's an issue, application level signaling could be added, but I don't think there's a general solution that works well for a wide variety of applications.
