### ISSUE TITLE
Congestion control

### ISSUE THREAD

**Issue by DavidSchinazi** [tfpauly/draft-pauly-quic-datagram#5]
We should add text on how DATAGRAM frames interact with congestion control. In particular they should be congestion controlled so an application that sends too much data will not flood the network.

**Comment by rpaulo** [comment]
They won't be able to flood the network.  An application can try to send DATAGRAM frames but they will be limited by the congestion window.  

The problem is that, since they are not ack-eliciting, we need to explain how the congestion window will actually grow.  If only one endpoint sends DATAGRAM frames, this endpoint will be congestion limited very quickly since the other side isn't sending ACKs.

**Comment by DavidSchinazi** [comment]
My point was that we should mention that DATAGRAM frames are indeed limited by the congestion window. Upon re-reading the draft, it is mentioned there, but we may just want to reiterate it to make sure that point is obvious.

DATAGRAM frames do elicit ACKs, the only difference is that those ACKs can be deferred and batched. We could mention that endpoints should not delay too much to prevent the other side from being congestion window limited.

**Comment by rpaulo** [comment]
I think (and I'm not the only one) that DATAGRAM frames should be ACK-eliciting but NOT retransmittable.  This way we keep the congestion window growing if only one endpoint is sending and if the network quality changes the protocol can react accordingly.

**Comment by DavidSchinazi** [comment]
I think we're all in agreement there.

**Comment by erickinnear** [comment]
Discussed in Prague Side Meeting: Strong consensus in the room was that DATAGRAM frames should be included in Congestion Control and should also be ACK-eliciting, yet not retransmittable.

**Comment by tfpauly** [comment]
Added text for this in #9
